//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3521
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVM.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Name - EpisodeNumber")]
        public string FileNamePattern {
            get {
                return ((string)(this["FileNamePattern"]));
            }
            set {
                this["FileNamePattern"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long LastParentGroup {
            get {
                return ((long)(this["LastParentGroup"]));
            }
            set {
                this["LastParentGroup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LastSelectedIndex {
            get {
                return ((int)(this["LastSelectedIndex"]));
            }
            set {
                this["LastSelectedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool YouTubeWebPlayer {
            get {
                return ((bool)(this["YouTubeWebPlayer"]));
            }
            set {
                this["YouTubeWebPlayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PaleGreen")]
        public global::System.Drawing.Color LastWatchedColor {
            get {
                return ((global::System.Drawing.Color)(this["LastWatchedColor"]));
            }
            set {
                this["LastWatchedColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HuluWebPlayer {
            get {
                return ((bool)(this["HuluWebPlayer"]));
            }
            set {
                this["HuluWebPlayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool NameColumnEnabled {
            get {
                return ((bool)(this["NameColumnEnabled"]));
            }
            set {
                this["NameColumnEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Name")]
        public string NameColumnLabel {
            get {
                return ((string)(this["NameColumnLabel"]));
            }
            set {
                this["NameColumnLabel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EpisodeNameColumnEnabled {
            get {
                return ((bool)(this["EpisodeNameColumnEnabled"]));
            }
            set {
                this["EpisodeNameColumnEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Episode")]
        public string EpisodeNameColumnLabel {
            get {
                return ((string)(this["EpisodeNameColumnLabel"]));
            }
            set {
                this["EpisodeNameColumnLabel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SeasonNumberColumnEnabled {
            get {
                return ((bool)(this["SeasonNumberColumnEnabled"]));
            }
            set {
                this["SeasonNumberColumnEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SeasonNumberColumnLabel {
            get {
                return ((string)(this["SeasonNumberColumnLabel"]));
            }
            set {
                this["SeasonNumberColumnLabel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EpisodeNumberColumnEnabled {
            get {
                return ((bool)(this["EpisodeNumberColumnEnabled"]));
            }
            set {
                this["EpisodeNumberColumnEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#")]
        public string EpisodeNumberColumnLabel {
            get {
                return ((string)(this["EpisodeNumberColumnLabel"]));
            }
            set {
                this["EpisodeNumberColumnLabel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VideoCodecColumnEnabled {
            get {
                return ((bool)(this["VideoCodecColumnEnabled"]));
            }
            set {
                this["VideoCodecColumnEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VideoCodecColumnLabel {
            get {
                return ((string)(this["VideoCodecColumnLabel"]));
            }
            set {
                this["VideoCodecColumnLabel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AudioCodecColumnEnabled {
            get {
                return ((bool)(this["AudioCodecColumnEnabled"]));
            }
            set {
                this["AudioCodecColumnEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AudioCodecColumnLabel {
            get {
                return ((string)(this["AudioCodecColumnLabel"]));
            }
            set {
                this["AudioCodecColumnLabel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ContainerColumnEnabled {
            get {
                return ((bool)(this["ContainerColumnEnabled"]));
            }
            set {
                this["ContainerColumnEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ContainerColumnLabel {
            get {
                return ((string)(this["ContainerColumnLabel"]));
            }
            set {
                this["ContainerColumnLabel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TimesPlayedColumnEnabled {
            get {
                return ((bool)(this["TimesPlayedColumnEnabled"]));
            }
            set {
                this["TimesPlayedColumnEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Played")]
        public string TimesPlayedColumnLabel {
            get {
                return ((string)(this["TimesPlayedColumnLabel"]));
            }
            set {
                this["TimesPlayedColumnLabel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int NameColumnWidth {
            get {
                return ((int)(this["NameColumnWidth"]));
            }
            set {
                this["NameColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int EpisodeNameColumnWidth {
            get {
                return ((int)(this["EpisodeNameColumnWidth"]));
            }
            set {
                this["EpisodeNameColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int SeasonNumberColumnWidth {
            get {
                return ((int)(this["SeasonNumberColumnWidth"]));
            }
            set {
                this["SeasonNumberColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int EpisodeNumberColumnWidth {
            get {
                return ((int)(this["EpisodeNumberColumnWidth"]));
            }
            set {
                this["EpisodeNumberColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("55")]
        public int VideoCodecColumnWidth {
            get {
                return ((int)(this["VideoCodecColumnWidth"]));
            }
            set {
                this["VideoCodecColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("55")]
        public int AudioCodecColumnWidth {
            get {
                return ((int)(this["AudioCodecColumnWidth"]));
            }
            set {
                this["AudioCodecColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("55")]
        public int ContainerColumnWidth {
            get {
                return ((int)(this["ContainerColumnWidth"]));
            }
            set {
                this["ContainerColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("55")]
        public int TimesPlayedColumnWidth {
            get {
                return ((int)(this["TimesPlayedColumnWidth"]));
            }
            set {
                this["TimesPlayedColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int NumberOfColumns {
            get {
                return ((int)(this["NumberOfColumns"]));
            }
            set {
                this["NumberOfColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Windows.Forms.ListView LastListView {
            get {
                return ((global::System.Windows.Forms.ListView)(this["LastListView"]));
            }
            set {
                this["LastListView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("imdb")]
        public string MoreInfoService {
            get {
                return ((string)(this["MoreInfoService"]));
            }
            set {
                this["MoreInfoService"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PromptOnDelete {
            get {
                return ((bool)(this["PromptOnDelete"]));
            }
            set {
                this["PromptOnDelete"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DoubleClickPlay {
            get {
                return ((bool)(this["DoubleClickPlay"]));
            }
            set {
                this["DoubleClickPlay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BackspaceDelete {
            get {
                return ((bool)(this["BackspaceDelete"]));
            }
            set {
                this["BackspaceDelete"] = value;
            }
        }
    }
}
